### ISSUE TITLE
DonneesOuvertes - HqDonneesOuvertes.yaml fails

### ISSUE THREAD

**Issue by baylanger** [MichelJourdain/HydroQuebec#1]
Hi,

I've got the [hq_open_data.yaml](https://github.com/djiesr/Hydro-Quebec_Open_Data/blob/main/hq_open_data.yaml) in place and got it working a while ago using this card https://github.com/djiesr/Hydro-Quebec_Open_Data/blob/main/apexcharts.yaml -

Somehow when I copy/paste HqDonneesOuvertes.yaml into a new card, the card isn't happy and the only err I get is : 

> i.lovelace.config.sak_user_templates is undefined

Would you know how to fix this one?

<img width="491" alt="2023-02-18_17-40-10" src="https://user-images.githubusercontent.com/5240348/219902566-3f3357e4-3c3f-4f0d-beb0-92ff7529b349.png">

Thanx for your great work!

**Comment by MichelJourdain** [comment]
Désolé, je n’avais pas mis le fichier de la template et il n’était pas indiqué dans les étapes d’installation. Le tout est corrigé.

https://github.com/MichelJourdain/HydroQuebec/tree/main/DonneesOuvertes

**Comment by baylanger** [comment]
J'ai ajoute le fichier et fait un restart. Toujours la meme erreur. Faut-il faire qq chose du genre "lovelace: !include" ?

```
$ cd config/
$ mkdir -p lovelace/sak_templates/templates/layouts
$ cd  lovelace/sak_templates/templates/layouts
$ curl https://raw.githubusercontent.com/MichelJourdain/HydroQuebec/main/DonneesOuvertes/sak_layout_mjt_periode_actuelle.yaml > sak_layout_mjt_periode_actuelle.yam
$ ls -l
-rw-r--r--    1 root     root          6946 Feb 18 18:02 config/lovelace/sak_templates/templates/layouts/sak_layout_mjt_periode_actuelle.yaml
```

Merci!

**Comment by baylanger** [comment]
ah il me manque peut-etre de la config pour swiss-army mais j'ai installe via hacs. Je dois preparer le souper, je vais passer au travers de la doc de swiss-army et les autres modules.

https://swiss-army-knife-card-manual.amoebelabs.com/start/installation/

**Comment by MichelJourdain** [comment]
Les template de base doivent être installer manuellement. L’installation HACS ne le fait pas. L’étape 2 à faire.

**Comment by baylanger** [comment]
Je crois avoir maintenant tout mis en place, voir en bas completement.

Cependant je n'utilise pas le mode "yaml", donc le fichier ui-lovelace.yaml n'est pas inclus. Je me casse le coco a trouver ou/comment ajouter les 2 "include". J'ai lu qu'il faut ajouter sous "resources:". J'ai essaye d'ajouter directment au dashboard en mode "raw" mais ca donne un erreur de yaml.

Je passerais bien ma config en mode "yaml" mais avant je vais devoir lire un peu (implication, etc). J'ai trouve des infos des un thread de 2019 , qui utilisait "url" au lieu de "include", peut-etre qu'il faut simplement utiliser url? A suivre....

Merci.

```
# Swiss Army Knife Templates
#
# The system templates come with the HACS install and can be updated
# with a new release. That part is automatic!
sak_sys_templates:
  !include www/community/swiss-army-knife-card/sak_templates.yaml

# The user templates are created by the user, and won't be updated 
# with a new release. If changes are required, then the user has to
# upate the template configuration files.
sak_user_templates:
  !include lovelace/sak_templates/sak_templates.yaml
```

```
$ find /config/lovelace -type f
/config/lovelace/sak_templates/definitions/user-css-definitions.yaml
/config/lovelace/sak_templates/colorstops-template.yaml
/config/lovelace/sak_templates/sak_templates.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-battery-level-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-boiler-water-blue-orange-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-temperature-inside-heating-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-temperature-inside-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-boiler-setpoint-blue-orange-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-humidity-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-airvisual-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-lux-template.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-energy-2kw.yaml
/config/lovelace/sak_templates/templates/colorstops/colorstops-pressure-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-tutorial-02-part1-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-light-button-slider-nm-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-light-button-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset_light_button_nm.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-light-button-slider2-nm-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-light-button-nm-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-arc180-sparklinebar24-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-electricity-delivered-returned-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-tutorial-01-part3-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-light-button-slider3-nm-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-sensor-history-template.yaml
/config/lovelace/sak_templates/templates/toolsets/toolset-segarc-icon-state-template.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-clippath-test.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-light-with-slider.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-tomorrow-pollen-all.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-scene.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-tomorrow-pollen-all-aqi.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-battery2.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-binary-alert1.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-switch1.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-battery1a.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-tomorrow-pollen.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-switch3.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-header.yaml
/config/lovelace/sak_templates/templates/layouts/sak_layout_mjt_periode_actuelle.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-navigate.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-light.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-server-statistics.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-power-outlet3.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-airvisual2.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-sensor1.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-sensor2.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-battery1b.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-person.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-input-boolean.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-binary-alert4.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-binary-alert2.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-switch2.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-power-outlet2.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-power-outlet4.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-environment.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-binary-alert3.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-sensor1a.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-binary.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-power-outlet1.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-airvisual1.yaml
/config/lovelace/sak_templates/templates/layouts/sak-layout-fce-sensor1b.yaml
/config/lovelace/sak_templates/templates/derived/derived-entity-brightness-template.yaml
/config/lovelace/sak_templates/templates/material3/toolset-m3-surface-colors-template.yaml
/config/lovelace/sak_templates/templates/material3/toolset-m3-palette-colors-template.yaml
/config/lovelace/sak_templates/templates/material3/toolset-m3-mode-colors-template.yaml
/config/lovelace/sak_templates/templates/material3/m3.yaml
/config/lovelace/resources/resources.yaml
```


 mais je n'utilise pas le mode "yaml" pour "love

**Comment by baylanger** [comment]
Apres avoir ecrit mon dernier message, j'ai fouille un peu. Il y a une section "resources" dans le menu des dashboard.

swiss-army, vertical-card-stack, etc... ils y sont tous. Cependant je ne trouve pas de reportoire "hacsfiles" - j'ai ajoute les 2 "include" mais j'avoue... sans surprise, ca n'a rien donnee. Je vais continuer demain/un autre jour.

<img width="959" alt="2023-02-18_21-32-11" src="https://user-images.githubusercontent.com/5240348/219908964-0c627bd3-05a8-4c4b-9cbd-27d8ceb81976.png">

**Comment by baylanger** [comment]
Je viens de remarquer que j'y mis "javascript" mais ce ne sont pas des fichiers "js".

**Comment by baylanger** [comment]
J'ai switche de "js" a "stylesheet" ... pas mieux :(   J'abandonne pour ce soir.

Merci encore.

**Comment by MichelJourdain** [comment]
Ça ne vous aidera probablement pas, mais moi j'utilise le Dwains Dashboard et j'ai ajouté l'appel des templates dans le fichier suivant. 

![6743D428-25BD-4FFC-9A67-0D178C41946E](https://user-images.githubusercontent.com/83040228/219909354-138ef935-364c-4f1a-b102-023ef9a3ca58.jpeg)

Je ne sais pas  comment faire dans votre cas. 😟

**Comment by baylanger** [comment]
Je me souviens d'avoir entrevue "Dwains Dashboard" - je vais voir si je peux ajouter sans trop casser ce que j'ai en place.

Merci cette info.

**Comment by MichelJourdain** [comment]
J’ai demandé à une personne qui l’avais installé sans Dwains Dashboard. Voici ça réponsse.

![AF4079B3-339D-411C-818D-C94C223B6E89](https://user-images.githubusercontent.com/83040228/219957009-2e221b69-5adb-426c-bf7f-d006bf70dea1.jpeg)
![D237FA67-3664-42E2-86B4-6878FCCE1BC8](https://user-images.githubusercontent.com/83040228/219957011-e91d86e3-c57a-4f30-a4c3-6ddfebe302db.jpeg)

**Comment by baylanger** [comment]
Oh mon dieu, j'aurais cherche encore longtemps :D 

Pour une raison inconnue, j'avais une erreur avec cette config dans le configuration.yaml

```
Invalid config for [lovelace]: expected a list for dictionary value @ data['lovelace']['resources']. Got OrderedDict(). (See /config/configuration.yaml, line 136). 
```

Apres reflexion, j'ai modifie "resources" pour en faire une liste. Ceci fonctionne tres bien (Youppi!). Je paste la config au cas ou tu veux ajouter aux instructions.

```
lovelace:
  mode: storage
  resources:
    - !include lovelace/resources/resources.yaml
  dashboards:
    hydro-quebec:
      filename: Hydro-Quebec.yaml
      title: Hydro-Quebec
      show_in_sidebar: true
      mode: yaml
```

```
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml
sak_sys_templates:
  !include www/community/swiss-army-knife-card/sak_templates.yaml
sak_user_templates:
  !include lovelace/sak_templates/sak_templates.yaml

title: Hydro-Quebec
views:
  - !include HqDonneesOuvertes.yaml
```

Pour le moment j'ai juste configure les donnees ouvertes.

Gros merci encore et bon dimanche.

**Comment by baylanger** [comment]
J'ai modifie le derniere commentaire pour ajouter "icon: mdi:flash".

**Comment by MichelJourdain** [comment]
Si vous le désirez, vous pouvez enlever cette ligne, les templates decluttering ne sont pas utiliser dans le tableau.

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

**Comment by baylanger** [comment]
Bonnee idee, je vais mettre en commentaire au cas ou plus tard j'en ai besoin.

On peut ferme ce "issue", merci encore pour votre aide!
